name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install xvfb
      run: |
        apt update
        apt install -y xvfb
    - name: Setup Bats and bats libs
      id: setup-bats
      uses: bats-core/bats-action@3.0.0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run bats test
      run: bats test/bats/x
      shell: bash
      env:
        BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        TERM: xterm
